# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addr',
            name='published_date',
        ),
        migrations.AddField(
            model_name='addr',
            name='first_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addr',
            name='last_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
