# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0002_auto_20180626_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addr',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='addr',
            name='last_name',
        ),
    ]
