# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0003_auto_20180626_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='phone1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='addr',
            name='phone2',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
