# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0004_auto_20180626_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addr',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='addr',
            name='phone2',
            field=models.CharField(blank=True, default=1, max_length=15),
            preserve_default=False,
        ),
    ]
