# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0007_auto_20180626_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='addr',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
