# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0008_addr_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='approved',
            field=models.NullBooleanField(),
        ),
    ]
